#include "headers/polynomial.h"
#include "headers/grothendieck_refined.h"
#include "headers/e.h"
#include "headers/det.h"
#include "headers/g_det_formula.h"
#include "headers/grassman.h"
#include "headers/bialternant.h"
#include "headers/SVT.h"
#include "headers/schur.h"
#include "headers/homogenous.h"
#include "headers/generate-partitions.h"
#include "headers/tab.h"
#include "headers/shrink_transformation.h"
#include "headers/generalized_dual_grothendieck_polynomial.h"

#include "G-expansion-experiment/grothendieck_expansion.h"

//#include "3D-LGV-experiments/3D-LGV.h"
//#include "3D-LGV-experiments/experiments.h"

#include "Symmetric-Equivalence-problem/JDT-plus-insert-algorithm.h"
